backend:
  name: github
  repo: ClementLSW/portfolio
  branch: main
  site_domain: magenta-tulumba-f45298.netlify.app

site_url: https://clementlsw.com

media_folder: public/images/projects
public_folder: /images/projects

collections:
  - name: blog
    label: Blog Posts
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: list }
      - { name: coverImage, label: Cover Image, widget: image, required: false }
      - { name: draft, label: Draft, widget: boolean, default: false }
      - { name: body, label: Body, widget: markdown }

  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: status, label: Status, widget: select, options: ["released", "in-progress", "prototype", "archived"] }
      - { name: featured, label: Featured, widget: boolean, default: false }
      - { name: event, label: Event, widget: string, required: false }
      - { name: role, label: Role, widget: string }
      - { name: coverImage, label: Cover Image, widget: image, required: false }
      - { name: draft, label: Draft, widget: boolean, default: false }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - name: about
        label: About
        file: src/content/pages/about.mdx
        extension: mdx
        format: frontmatter
        fields:
          - { name: title, label: Title, widget: string }
          - { name: body, label: Body, widget: markdown }
    
      - name: now
        label: Now
        file: src/content/pages/now.mdx
        extension: mdx
        format: frontmatter
        fields:
          - { name: title, label: Title, widget: string }
          - { name: lastUpdated, label: Last Updated, widget: datetime }
          - { name: body, label: Body, widget: markdown }